### ISSUE TITLE
Bower dependencies

### ISSUE THREAD

**Issue by oracleruiz** [jamesallardice/Placeholders.js#70]
I'm using bower to download the lib and used it. But I'm not able to find the proper .js to include in my webpage. Could you please but the assets in the github repository?

**Comment by avindra** [comment]
Bower support would be great for builds, including the jquery adapters (and others). Having to manually download and install dependencies seems legacy now with all of the package managers out there.

**Comment by jamesallardice** [comment]
I have finally got around to sorting this out. Version 4.0.0 is available through Bower now.
