### ISSUE TITLE
'Placeholders' is undefined in IE8 with jQuery adapter

### ISSUE THREAD

**Issue by tommedema** [jamesallardice/Placeholders.js#78]
When including placeholders.jquery.min.js after jQuery the following error is shown in Internet Explorer 8:

`'Placeholders' is undefined`

I've traced this back to [line 8 of the jQuery adapter](https://github.com/jamesallardice/Placeholders.js/blob/master/lib/adapters/placeholders.jquery.js#L8). I'm not sure why Placeholders is not defined here though. Perhaps an explicit call to window.Placeholders is necessary?

If you need more information to resolve this please tell.

**Comment by jamesallardice** [comment]
Closing this now. Apologies for not getting back to you sooner. As of version 4.0.0 the built files are included in the repository. You can see that the built adapter files include the main script too so you should be able to simply include the relevant adapter file on its own and this should no longer be an issue.
