### ISSUE TITLE
Force javascript placeholder even if browser supports placeholder

### ISSUE THREAD

**Issue by bolau** [jamesallardice/Placeholders.js#80]
Hi, thanks for the nice work on this polyfill. I want to use it mainly on mobile browsers (iOS and Android), which do support placeholders, but very limited support to style the placeholders. For example, right-aligning does not work there.
Is it possible to force the use of the polyfill even if the browser supports them natively?

Thanks for any help
Boris

**Comment by jamesallardice** [comment]
Unfortunately that is not possible and there are no plans to make it possible. Placeholders.js aims to be a true polyfill in that it seamlessly provides missing browser functionality but doesn't attempt to force all user agents to behave the same way. The spec allows for vendor interpretation of how placeholders should be handled.
