### ISSUE TITLE
placeholders events aren't bound on cloned inputs

### ISSUE THREAD

**Issue by Iftahh** [jamesallardice/Placeholders.js#85]
I'm using `$('.template').clone()` to add new dynamic rows to a form - these rows have several inputs with placeholders.  
The new added inputs have the placeholder text (in grey font color) but their events aren't working, eg. it isn't cleared when typed and the font color remains grey.

The workaround solution I used was to use a temporary attribute in the template and rename it after cloning:
```
var $new_row = $('.template').clone();
$new_row.attr('placeholder', $new_row.attr('tmp_placeholder'));
$new_row.removeAttr('tmp_placeholder');
$container.append($new_row);   
```

**Comment by jamesallardice** [comment]
Assuming `$` in this case is jQuery, the docs for [`clone`](https://api.jquery.com/clone/) state that events will not be cloned by default. I don't think this is a problem with Placeholders.js. If I've misunderstood and this is still an issue let me know and I'll reopen.
