### ISSUE TITLE
Github site went dead

### ISSUE THREAD

**Issue by tobi-or-not** [jamesallardice/Placeholders.js#88]
I just noticed that http://jamesallardice.github.io/Placeholders.js went dead. Is this on purpose? I used to retrieve my assets from there (http://jamesallardice.github.io/Placeholders.js/assets/js/placeholders.jquery.js)

Is there a new site coming or is the old site going to be back up?

**Comment by joesnellpdx** [comment]
I noticed the same thing. The link to "our new website is dead:
http://jamesallardice.github.io/Placeholders.js/

Any word on when you will have this back online?

**Comment by jamesallardice** [comment]
I'm not really sure what happened here but the site came back as soon as I pushed the `gh-pages` branch. I'm guessing GitHub did something that accidentally broke the page.
