### ISSUE TITLE
ie7 input type password can not use

### ISSUE THREAD

**Issue by ghost** [jamesallardice/Placeholders.js#91]
![image](https://cloud.githubusercontent.com/assets/3073370/8050170/28b1b7a6-0e9b-11e5-88a9-b9748a3de12e.png)

**Comment by yangkennyk** [comment]
password field doesn't populate with placeholder text on ie8 and below.

![password field](https://cloud.githubusercontent.com/assets/6680040/8172468/aabbf656-1375-11e5-9b2a-9f461499eca2.PNG)

**Comment by jamesallardice** [comment]
Unfortunately this is a known issue that will not be resolved. Please see #6 and all the linked issues for various discussions around this.
